// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKANDPgL8jVA8ZQ8TvO56nfggT7jWBozI',
    appId: '1:19263440841:web:f5df40eb42ce2b1c588a18',
    messagingSenderId: '19263440841',
    projectId: 'fir-flutter-codelab-cb3a9',
    authDomain: 'fir-flutter-codelab-cb3a9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-cb3a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAamQ-oGGP3A_gWuI06iby0OcIC00sxxE',
    appId: '1:19263440841:android:935a34cf207c8252588a18',
    messagingSenderId: '19263440841',
    projectId: 'fir-flutter-codelab-cb3a9',
    storageBucket: 'fir-flutter-codelab-cb3a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVOIiAbDhj1QTtcJl7THsrOfYG6o3Vxpw',
    appId: '1:19263440841:ios:f5edf06f9657db51588a18',
    messagingSenderId: '19263440841',
    projectId: 'fir-flutter-codelab-cb3a9',
    storageBucket: 'fir-flutter-codelab-cb3a9.appspot.com',
    iosClientId: '19263440841-091ngpovcmffdndmkdupe9at9n9j0tof.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVOIiAbDhj1QTtcJl7THsrOfYG6o3Vxpw',
    appId: '1:19263440841:ios:f5edf06f9657db51588a18',
    messagingSenderId: '19263440841',
    projectId: 'fir-flutter-codelab-cb3a9',
    storageBucket: 'fir-flutter-codelab-cb3a9.appspot.com',
    iosClientId: '19263440841-091ngpovcmffdndmkdupe9at9n9j0tof.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
